server:
  port: 10011
spring:
  application:
    name: ly-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wodaoanran/leyou.git
  rabbitmq:
    host: 127.0.0.1
    username: leyou
    password: leyou
    virtual-host: /leyou

management: #暴露出发消息总线的地址
  endpoints:
    web:
      exposure:
        exclude: bus-refresh