server:
  port: 10010
spring:
  application:
    name: api-gateway
  rabbitmq:
    host: 127.0.0.1
    username: leyou
    password: leyou
    virtual-host: /leyou

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5

  instance:
    prefer-ip-address: true #true 表示将ip地址注册到eureka false表示将主机名注册到eureka
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}



zuul:
  prefix: /api # 添加路由前缀
  retryable: true
  routes:
    item-service: /item/**  #商品微服务
    search-service: /search/**  #搜索微服务
    user-service: /user/**  #用户微服务
    auth-service: /auth/** #授权中心微服务
    cart-service: /cart/** #购物车微服务
    order-service: /order/** #订单微服务
  ignored-services:
    - upload-service # 忽略upload-service服务
  add-host-header: true #携带请求本身的head头信息
  sensitive-headers: #匹配禁止使用的头信息，这里设置为null，否则set-cookie无效

ribbon:
  ConnectTimeout: 60000 # 连接超时时间(ms)
  ReadTimeout: 60000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 熔断超时时长：10000ms
leyou:
  jwt:
    secret: leyou@Login(Auth}*^31)&heiMa% # 登录校验的密钥
    pubKeyPath: F:\\tmp\\rsa\\rsa.pub # 公钥地址
    priKeyPath: F:\\tmp\\rsa\\rsa.pri # 私钥地址
    expire: 30 # 过期时间,单位分钟
    cookieName: LY_TOKEN
    cookie-max-age: 30
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item
